# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0abcc7a78501db86ac31b53df911c120acc5d103f3ed7e5b4346f3dc71c25f1cc071d59d13782def1e0e2f192b2b13f14c36e2e8e363e217303268b2d4570aed

test:
  secret_key_base: 2f6794917dc9ca6eb6b03f6d1002ab71e8c6a8d0c5ad7e53223f49af78e1106db07c200a8232e371825e80f2858d83c82efafcfd83ce6285cef21655de3a29fc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
